{
 "title": "demoservice",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "99th percentile request latency in ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " histogram_quantile(0.99, sum(rate(demoservice_timer2_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Apdex with  SLA of 500ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\n(\n  sum(rate(demoservice_timer2_seconds_bucket{le=\"0.5\"}[5m])) \n  +\n  sum(rate(demoservice_timer2_seconds_bucket{le=\"1.0\"}[5m])  ) / 2 \n)\n  / sum(rate(demoservice_timer2_seconds_count[5m])) \n"
    }
   ]
  },
  {
   "title": "Avg-5m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(demoservice_timer2_seconds_sum[5m]))/\nsum(rate(demoservice_timer2_seconds_count[5m]))"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "demoservice_timer2_seconds" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(demoservice_timer2_seconds_bucket[10s])"
    }
   ]
  },
  {
   "title": "Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "demoservice status",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 5, "x": 1, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "up{instance=\"localhost:9001\",job=\"demoservice-app\"}"
      }
     ]
    },
    {
     "title": "Person-app status",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 5, "x": 6, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "up{instance=\"localhost:9000\",job=\"person-app\"}"
      }
     ]
    },
    {
     "title": "error increase",
     "type": "graph",
     "gridPos": { "h": 5, "w": 10, "x": 11, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(logback_events_total{level=\"error\"}[1m]))"
      }
     ]
    },
    {
     "title": "beat1",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 1, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "demoservice_heartbeat_beat1_total",
       "legendFormat": "beat1"
      }
     ]
    },
    {
     "title": "beat2",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 6, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "demoservice_heartbeat_beat2_total"
      }
     ]
    },
    {
     "title": "demoservice heartbeats",
     "type": "graph",
     "gridPos": { "h": 5, "w": 10, "x": 1, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "demoservice_heartbeat_beat1_total",
       "legendFormat": "beat1"
      },
      {
       "expr": "demoservice_heartbeat_beat2_total",
       "legendFormat": "beat2"
      }
     ]
    }
   ]
  }
 ]
}