global:
  scrape_interval: '5s'
  evaluation_interval: '5s'

scrape_configs:
  - job_name: 'demoservice-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['worker_9001:9001']

