{
 "title": "demoservice",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "2s",
 "panels": [
  {
   "title": "demoservice status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 1, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=\"worker_9001:9001\",job=\"demoservice-app\"}"
    }
   ]
  },
  {
   "title": "Person-app status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=\"worker_9001:9000\",job=\"person-app\"}"
    }
   ]
  },
  {
   "title": "Jvm buffer memory used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{id=\"direct\",instance=\"worker_9001:9000\",job=\"person-app\"}",
     "legendFormat": "person-app"
    },
    {
     "expr": "jvm_buffer_memory_used_bytes{id=\"direct\",instance=\"worker_9001:9001\",job=\"demoservice-app\"}",
     "legendFormat": "demoservice-app"
    }
   ]
  },
  {
   "title": "beat1",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 1, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "demoservice_heartbeat_beat1_total",
     "legendFormat": "beat1"
    }
   ]
  },
  {
   "title": "beat2",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "demoservice_heartbeat_beat2_total"
    }
   ]
  },
  {
   "title": "demoservice heartbeats",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 1, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "demoservice_heartbeat_beat1_total",
     "legendFormat": "beat1"
    },
    {
     "expr": "demoservice_heartbeat_beat2_total",
     "legendFormat": "beat2"
    }
   ]
  }
 ]
}