#Global configurations
global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.

scrape_configs:
  - job_name: 'demoservice-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:9001']